# Generated by Django 5.2.11 on 2026-04-04 07:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                            ("hackathon", "Hackathon"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("ai_ml", "AI & Machine Learning"),
                            ("web", "Web Development"),
                            ("mobile", "Mobile Development"),
                            ("data", "Data Science"),
                            ("cloud", "Cloud & DevOps"),
                            ("security", "Cybersecurity"),
                            ("iot", "IoT"),
                            ("blockchain", "Blockchain"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "seats",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("available_seats", models.IntegerField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_posters/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("event_registered", "Event Registered"),
                            ("event_cancelled", "Event Cancelled"),
                            ("registration_cancelled", "Registration Cancelled"),
                            ("payment_confirmed", "Payment Confirmed"),
                            ("payment_failed", "Payment Failed"),
                            ("team_accepted", "Team Accepted"),
                            ("team_invitation", "Team Invitation"),
                            ("event_reminder", "Event Reminder"),
                            ("promotion", "Promotion"),
                            ("recommendation", "Event Recommendation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_registrations", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("team_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "organizer_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("upi", "UPI"),
                            ("net_banking", "Net Banking"),
                            ("wallet", "Digital Wallet"),
                            ("simulation", "Simulated Payment"),
                        ],
                        default="simulation",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                            ("hackathon", "Hackathon"),
                            ("ai_ml", "AI & Machine Learning"),
                            ("web_dev", "Web Development"),
                            ("mobile_dev", "Mobile Development"),
                            ("data_science", "Data Science"),
                            ("cloud", "Cloud & DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("iot", "IoT"),
                            ("blockchain", "Blockchain"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("category_match", "Category Match"),
                            ("interest_match", "Interest Match"),
                            ("friend_attending", "Friend Attending"),
                            ("trending", "Trending Event"),
                            ("organizer_follow", "Following Organizer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=200)),
                (
                    "max_members",
                    models.IntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("leader", "Leader")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="organizerprofile",
            name="license_image",
            field=models.ImageField(blank=True, null=True, upload_to="license_images/"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="event_enroll_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(4.0),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="organizerprofile",
            index=models.Index(
                fields=["organization_type"], name="accounts_or_organiz_6d7286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["student_id"], name="accounts_st_student_942d8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["graduation_year"], name="accounts_st_graduat_0b57b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4734df_idx"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "organizer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizeranalytics",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="organizeranalytics",
            name="organizer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "organizer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentinterest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentrecommendation",
            name="recommended_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_recommendations",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="studentrecommendation",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={"event_type": "hackathon"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="accounts.event",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="led_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.team",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "status"], name="accounts_ev_organiz_05fe73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type"], name="accounts_ev_event_t_913457_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["category"], name="accounts_ev_categor_bf5e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="accounts_ev_date_03cd50_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="accounts_ev_status_60a88d_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_sent"], name="accounts_no_user_id_39a3ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="accounts_no_notific_6d2f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="accounts_no_created_caf92d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizeranalytics",
            index=models.Index(
                fields=["organizer"], name="accounts_or_organiz_e34816_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizeranalytics",
            unique_together={("organizer", "event")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="accounts_pa_user_id_618f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["event"], name="accounts_pa_event_i_1f93f7_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="accounts_pa_created_c3fc2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["user", "status"], name="accounts_re_user_id_006a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["event", "status"], name="accounts_re_event_i_8379ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                fields=["registered_at"], name="accounts_re_registe_277639_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("user", "event")},
        ),
        migrations.AddIndex(
            model_name="studentinterest",
            index=models.Index(
                fields=["student", "interest"], name="accounts_st_student_3f2f6d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentinterest",
            unique_together={("student", "interest")},
        ),
        migrations.AddIndex(
            model_name="studentrecommendation",
            index=models.Index(
                fields=["student", "created_at"], name="accounts_st_student_c43192_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentrecommendation",
            unique_together={("student", "recommended_event")},
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["event", "status"], name="accounts_te_event_i_a212a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_lead"], name="accounts_te_team_le_de807c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("event", "team_name")},
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "role"], name="accounts_te_team_id_0c3099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["user"], name="accounts_te_user_id_87327a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
    ]
