# Generated by Django 5.2.11 on 2026-04-04 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_event_notification_organizeranalytics_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Event must be approved by admin to be visible"
            ),
        ),
    ]
