# Generated by Django 5.2.11 on 2026-04-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_event_approved_at_event_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Invitation message", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Invitation expires after 7 days"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Why do you want to join this team?",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Rejection reason if rejected", null=True
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="description",
            field=models.TextField(
                blank=True, help_text="Team description and goals", null=True
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for joining team",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_registered", "Event Registered"),
                    ("event_cancelled", "Event Cancelled"),
                    ("registration_cancelled", "Registration Cancelled"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("payment_failed", "Payment Failed"),
                    ("team_join_request", "Team Join Request"),
                    ("team_join_request_accepted", "Team Join Request Accepted"),
                    ("team_join_request_rejected", "Team Join Request Rejected"),
                    ("team_invitation", "Team Invitation"),
                    ("team_invitation_accepted", "Team Invitation Accepted"),
                    ("team_invitation_rejected", "Team Invitation Rejected"),
                    ("team_member_joined", "Team Member Joined"),
                    ("team_member_left", "Team Member Left"),
                    ("event_reminder", "Event Reminder"),
                    ("promotion", "Promotion"),
                    ("recommendation", "Event Recommendation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_code"], name="accounts_te_team_co_c4dd64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["visibility"], name="accounts_te_visibil_1ae85a_idx"
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_team_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="accounts.team",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="accounts.team",
            ),
        ),
        migrations.AddField(
            model_name="teamjoinrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_join_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["team", "status"], name="accounts_te_team_id_3f09c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["invited_user", "status"], name="accounts_te_invited_00c823_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(fields=["status"], name="accounts_te_status_770185_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together={("team", "invited_user")},
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(
                fields=["team", "status"], name="accounts_te_team_id_13f702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(
                fields=["user", "status"], name="accounts_te_user_id_d18dd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamjoinrequest",
            index=models.Index(fields=["status"], name="accounts_te_status_f8b0ae_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="teamjoinrequest",
            unique_together={("team", "user")},
        ),
    ]
