# Generated by Django 5.2.11 on 2026-04-05 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_teaminvitation_teamjoinrequest_team_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("badge", "Badge"),
                            ("certificate", "Certificate"),
                            ("award", "Award"),
                            ("participation", "Participation"),
                        ],
                        default="badge",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon name, e.g., trophy, star",
                        max_length=100,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_achievements",
                        to="accounts.event",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "achievement_type"],
                        name="accounts_st_student_285794_idx",
                    ),
                    models.Index(
                        fields=["earned_at"], name="accounts_st_earned__9421b7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("cpp", "C++"),
                            ("react", "React"),
                            ("nodejs", "Node.js"),
                            ("django", "Django"),
                            ("sql", "SQL"),
                            ("mongodb", "MongoDB"),
                            ("docker", "Docker"),
                            ("kubernetes", "Kubernetes"),
                            ("aws", "Amazon AWS"),
                            ("azure", "Microsoft Azure"),
                            ("gcp", "Google Cloud"),
                            ("git", "Git"),
                            ("agile", "Agile"),
                            ("problem_solving", "Problem Solving"),
                            ("communication", "Communication"),
                            ("teamwork", "Teamwork"),
                            ("leadership", "Leadership"),
                            ("project_management", "Project Management"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "level"],
                        name="accounts_st_student_043891_idx",
                    )
                ],
                "unique_together": {("student", "skill")},
            },
        ),
    ]
